language: node_js
node_js:
- '12'
- '10'
- '8'
deploy:
  provider: npm
  email: wouter.dullaert@gmail.com
  api_key:
    secure: "m7ox8u/YFBKXpC4oGwpgVNalZy0Wjc1ULEwUh24lJVMRXa89N4geAqObov8tm4FIV784U32Q7/vHM6Z60FadcfwjE8vsZ++irbk7dV5RzAhJZXpZefpITYu6U9snH17mbfebzP3sU6PCbSE93blFyeFHx/auG5nqerYn0f/xlqcE4NKFKgSKcw3UycrW6PolpIg4CcjZqn+y4wnCfkJEuX9ovKHl8SNE7gIMkL17AFx97nnO4jZsmyQTBlkNk5FX2RJA2Oowpy2JEpYoGi8cxy5Bh0TUG1KJ8LSIswzDV5iWxYQAOniNvj0MMKTzAHNtDmWOvYasNYYUBRqZ/TpSJ1TxJWVpHxNOmQUti9Ssxk39WIobG5crCjrbjbb7i0O1DwYamsn7qUTCg5zXN03R+nSONcuNugXAQMaqCMFWh5NifQyd+p8c46LhxRF5RSANPypTl9HMsavG9NS9az4VAOzmYzB8P7DTX80jxNkDVu7zik/8x1jNoHtSmg8CNggMqB8F7cYEW4xyyH2OjlQUwgzwSi/bF1ovE9TfnvFigUyOVtRbR2Jm9pSbkZLMusmLAVCVlJpXe8JXeP4ouGkVn08umgJR2hEIqqsaJD41/HfP7Peu2C2Rr+PfbcOTsFQ9hvr/FiT7ZG9Js2k7U3b8NRXReH1D5NVMR/pYI/sZ24o="
  skip_cleanup: true
  on:
    tags: true
    node: '10'
